# Stripe CLI Configuration
# Commands and their key requirements
# key: "secret" (sk_*) or "restricted" (rk_*)
# Default for unlisted commands: "restricted"

# Global settings
global:
  default_platform: "vet"
  test_platform: "vet"

# Platform configurations
platform:
  vet:
    account: "acct_18yYltEdgy9m3MPr"
    connected_account: "acct_1MzSRtROT734hn6m"

  vet-uat:
    mode: "test"
    connected_account: "acct_1Rw31tRLzvnMBwNL"    

  # Daysmart production profile
  daysmart:
    account: "acct_1LLF4ZFUW1wgLnXK"
    
  # Daysmart test profile (separate from production)
  daysmart-uat:
    account: "acct_1LLF4ZFUW1wgLnXK"
    connected_account: "acct_1MMHptFa2mkwl760"

  # Daysmart production profile
  dash-uat:
    account: "acct_1Lq7dbK4siagmU0S"
    connected_account: "acct_1NJ1GmGbCZLRoQrm"

  ttp:
    account: "acct_1EN24zFPddEoAyG1"

commands:
  "account.setting.network-cost.enable":
    key: "secret"
    test_env: prod
  "account.setting.network-cost.disable":
    key: "secret"
    test_env: prod
  "account.setting.network-cost.status":
    key: "secret"
    test_env: prod
  "account.setting.network-cost.delete-scheme":
    key: "secret"
    test_env: prod
  "account.search":
    key: "restricted"
  "test.account.generate":
    key: "secret"
  "account.capabilities.request":
    key: "restricted"
  "account.capabilities.list":
    key: "restricted"
  "account.customer.delete":
    key: "restricted"
  # Add more commands here as needed
  # "account.list":
  #   key: "restricted"
  # "account.import.card":
  #   key: "restricted"